### ISSUE TITLE
Upstream the plugin

### ISSUE THREAD

**Issue by easyteacher** [dark-eye/com.darkeye.animatedImage#10]
Hello author, 

Do you have interest upstreaming your wallpaper plugin? I can help integrate the plugin with the default image wallpaper plugin.

Thanks!

**Comment by SimPilotAdamT** [comment]
He's gone pretty quiet... If you were to fork it for KDE use, it wouldn't go against the license...

**Comment by dark-eye** [comment]
@easyteacher  Go  for it...
would be happy  to be involved withthe process if  i can help in anyway

**Comment by easyteacher** [comment]
I would like to ship the default animated image in Plasma 5.26 Beta, is it possible? What license does it use?

**Comment by dark-eye** [comment]
It`s my  video so it`s under GPL  theoretically, as it was uploaded to this  project.
But lets say it`s also CC if need.

**Comment by dark-eye** [comment]
@easyteacher where  does it  upstreamed too  maybe i can help :)

**Comment by SimPilotAdamT** [comment]
> @easyteacher where does it upstreamed too maybe i can help :)

The capability to do animated walls has already been implemented in the 5.26 beta so I suspect it's already been added. There are nowhere near as many customization options though...

**Comment by dark-eye** [comment]
@easyteacher great! can't wait to see it on my desktop :)
