### ISSUE TITLE
Broken by Plasma 5.25

### ISSUE THREAD

**Issue by SimPilotAdamT** [dark-eye/com.darkeye.animatedImage#11]
In KDE Plasma version 5.25, this completely breaks. It becomes impossible to set any wallpaper through this...

Screenshot:
![image](https://user-images.githubusercontent.com/71192298/173883281-59a77563-4184-4600-bec3-9f5be036d844.png)

**Comment by mrdev023** [comment]
I fix it https://github.com/mrdev023/com.darkeye.animatedImage

**Comment by mrdev023** [comment]
https://github.com/dark-eye/com.darkeye.animatedImage/pull/13

**Comment by SimPilotAdamT** [comment]
> I fix it https://github.com/mrdev023/com.darkeye.animatedImage

Thanks for the fix, though it did not actually work on my machine...

**Comment by mrdev023** [comment]
Did you uninstall the extension before?

**Comment by SimPilotAdamT** [comment]
> Did you uninstall the extension before?

yep, uninstalled, rebooted, installed from your master branch

**Comment by mrdev023** [comment]
I need more informations:

* KDE Frameworks version
* KDE Plasma version
* OS Name
* OS Version

@SimPilotAdamT

**Comment by dark-eye** [comment]
Sorry it took  me so long to get to it....
 PR merged
