### ISSUE TITLE
Cannot apply wallpaper settings

### ISSUE THREAD

**Issue by Snogard** [dark-eye/com.darkeye.animatedImage#14]
### System
OS: Archlinux
Kernel: 6.0.6 zen
KDE: 5.26.2

### Problem
I cannot apply my wallpaper settings with this plugin

### How to reproduce:
1. Open configure desktop and wallpaper
2. Select "Animated Image" on the "Wallpaper type" field
3. Select any image
4. Click "Apply"

Now the image is selected, you have the preview on the window but not on the desktop and clicking apply does not work.
Clicking "OK" yields the same result exept that it also closes the window as expected.

**Comment by dark-eye** [comment]
@Snogard Issue should be fixed in v0.3.2.
If it persists please update me and i`ll  try and resolve it

**Comment by Snogard** [comment]
I first tried updating it from discover and it didn't work. I then tried removing and reinstalling it, and it finally worked!
Thank you very much.
