### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by Z-Y00** [dark-eye/com.darkeye.animatedImage#3]
Hi, I tried it with a gif of 67.8M size, and I was shocked that I got an OOM, I will send you the gif I used if you need it to test.

**Comment by Z-Y00** [comment]
I guess this is due to this
https://github.com/dark-eye/com.darkeye.animatedImage/blob/415a1c3cf68194f796113037798ffb958da40a2f/contents/ui/BackgoundComponent.qml#L32

I guess this is too large? Btw, I converted the gif from a mp4 file.
``` 
			cache:(frameCount && sourceSize.height*sourceSize.width*frameCount*4 < 2^26)
			onSourceSizeChanged:{
				cache = (frameCount && sourceSize.height*sourceSize.width*frameCount*4 < 2^26) //only cache if its fairly inexpensive
			}
```

**Comment by dark-eye** [comment]
Yeah it might be too large you can try and convert it to .webp which should be smaller :
`
ffmpeg <source file > -loop 0 <output file>.webp
`
but it might (will) cuase high CPU load ...
(I`m working on pausing the animation when the desktop is completely covered....)
